- name: create squid directory
  file: path=/opt/squid state=directory

- name: changing the squid directory
  command: chdir=/opt/squid ls

- name: gets rpm packages
  get_url:
    url={{ item }}
    dest=/opt/squid/
  with_items:
    - "{{ perl_crypto_url }}"
    - "{{ squid_url }}"
    - "{{ squid_debug_url }}"
    - "{{ squid_helper_url }}"
  register: get_url_result
  until: get_url_result|success
  retries: 5
  delay: 109 

- name: install perl crypto rpm package
  yum:
    name: /opt/squid/{{ item }}
    state: present
  with_items:
    - "{{ perl_rpm_name }}"
    - "{{ squid_rpm_name }}"
    - "{{ squid_debug_rpm_name }}"
    - "{{ squid_helper_rpm_name }}"
  when: get_url_result|changed

- name: add lines to squid
  lineinfile:
    dest: /etc/squid/squid.conf
    line: "{{ item }}"
  with_items:
    - "cache_dir ufs /var/spool/squid 100 16 256"
    - "cache_effective_user squid"

- name: making squid directories in cache
  shell: '/usr/sbin/squid -z'

- name: Make sure a service is running
  systemd: state=started name=squid

