---
- name: yum | enable epel repository
  shell: 'orange-yumconf -e "{{ item }}"'
  with_items:
    - "{{ repo1 }}" 
    - "{{ repo2 }}" 
    - "{{ repo3 }}" 

- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no
  
- name: yum makecache fast
  shell: 'yum makecache fast'
  ignore_errors: yes

- name: Install list of packages
  yum: name={{ item }} state=installed
  with_items:
    - wget
    - gcc
    - flex
    - bison
    - zlib
    - zlib-devel
    - libpcap
    - libpcap-devel
    - pcre
    - pcre-devel
    - tcpdump
    - mysql
    - mysql-devel
    - git
    - libtool
    - curl
    - man
    - libdnet
    - libdnet-devel
    - net-snmp
    - net-snmp-utils
